[package]
name = "calc"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
log = { version = "0.4", features = ["release_max_level_error"] }
num_enum = "0.7"
once_cell = "1.20"
strum = "0.26"
strum_macros = "0.26"
pak = { path = "../src-pak" }
